# Generated by Django 6.0.7 on 2026-07-26 08:21

import core.utils.upload_paths
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_award_galleryimage_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='x_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to=core.utils.upload_paths.album_cover_path),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_paths.artist_favicon_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(upload_to=core.utils.upload_paths.artist_profile_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_paths.award_image_path),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.upload_paths.country_flag_path),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_paths.gallery_image_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_paths.news_image_path),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(upload_to=core.utils.upload_paths.site_favicon_path),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(upload_to=core.utils.upload_paths.site_logo_path),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('x', 'X'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('soundcloud', 'SoundCloud'), ('threads', 'Threads')], max_length=30)),
                ('url', models.URLField()),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.artist')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('artist', 'social_network'), name='unique_artist_social_network')],
            },
        ),
    ]
